### ISSUE TITLE
NC 17.0 - Problem with the size of the display of some graphics in Admin Settings => System

### ISSUE THREAD

**Issue by Microcrap** [nextcloud/serverinfo#158]
![Screenshot_2019-10-05_13-10-21](https://user-images.githubusercontent.com/56029538/66254149-b0cca380-e772-11e9-9ee2-cc040a3bb116.png)

### Steps to reproduce
1. Go to Admin Settings => System
2. See the graph, "Share" and "Active User" can't be read, they are so little

### Server configuration

**PHP version:** 7.2

**Nextcloud version:** 17.0

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Comment by j-ed** [comment]
I can confirm this problem. The mentioned graphs are unusable/unreadable at the moment.

**Comment by j-ed** [comment]
See also https://github.com/nextcloud/serverinfo/issues/155

**Comment by Bables55** [comment]
This happens even after NC18.0.0.

**Comment by simonspa** [comment]
I see the fix for this was merged via #185 - but I haven't found a backport of this for 18.0.4 - is this planned?

**Comment by kesselb** [comment]
Fixed by #164 / #185 for Nextcloud 19. To much changes for a backport.

**Comment by simonspa** [comment]
Alright, thanks for fixing and letting us know! Looking forward to the next release then. :)

**Comment by arnowelzel** [comment]
JFTR: I still have this problem with NC 19, just in a different way now:

![grafik](https://user-images.githubusercontent.com/6613614/90485571-fbab9b80-e137-11ea-933b-757628872a6f.png)

**Comment by arnowelzel** [comment]
JFTR: I still(!) have this issue with of NC 20.0.3:

![grafik](https://user-images.githubusercontent.com/6613614/103351180-a6e33e80-4aa2-11eb-9028-d42caf9cb916.png)

What can I do to fix this? In other installations of the same version this does not happen.

This happens with every browser I tested. Any caches on the server side which I could clear?
